export default [
  '8J2Y3A',
  'PZA95Q',
  'RGGNBQ',
  'GEQH3J',
  'N5DG5G',
  '4PK74S',
  '8UZ7YD',
  'DDQKML',
  '7WFN5A',
  'A3UD6P',
  'JMGRV8',
  'B3PWCT',
  'HJPJFK',
  'Q76TAR',
  'QLPZ8H',
  'RXUB25',
  '6YXR9P',
  'NBA8XY',
  'NHSNTT',
  'KYQ39L',
  'Q48AXP',
  'QXE4ZZ',
  'WDH7B3',
  'SYLSLX',
  'QEXDHC',
  'F3B2ZZ',
  'KTKDDN',
  '2XYM8V',
  'UCW9FR',
  'KAYFE4',
  'KFLP24',
  'QMU3MY',
  'KBN6JM',
  'JPGMR2',
  '77PN64',
  'BLXN2Y',
  'AY6CH5',
  'N95R2Q',
  'V5JGZX',
  'RY2L3Y',
  '428M2F',
  'U6A7HS',
  'FKKM7D',
  'ZD84Y9',
  'CE4H79',
  'AQAZT6',
  'AHQBN5',
  'Y7VQ5Y',
  '4RNMT4',
  '4FJYD3',
  'V62JYA',
  'VU727U',
  'CD3BQX',
  '5NS47Q',
  'WNTBV3',
  'JXHDV4',
  '24XQUH',
  'VPEKML',
  '9R8LSS',
  'ZB26ML',
  'DF27YR',
  'SJZNQF',
  '2XAWY4',
  'JXQFUN',
  'PKQ77R',
  'WGHRKR',
  'QYHPNQ',
  'J64DUA',
  'XAJ9G9',
  '534BYJ',
  'FDWT5P',
  'JFM8AR',
  'YA9KPD',
  'CXLTVN',
  '7UG6KR',
  'V542YU',
  'PLE44H',
  'S9PSFG',
] as const;

export const thaiNumber = ['๐', '๑', '๒', '๓', '๔', '๕', '๖', '๗', '๘', '๙'];
export interface lookup {[k: string]: string[]}
export const toCharMap = (refcodes: string[]): [lookup, lookup, lookup, lookup, lookup, lookup] => (
  [0, 1, 2, 3, 4, 5] as [number, number, number, number, number, number]
).map(
  (i) => refcodes.reduce<lookup>((acc, refcode) => ({ ...acc, [refcode.charAt(i)]: (acc[refcode.charAt(i)] || []).concat(refcode) }), {}),
) as unknown as [lookup, lookup, lookup, lookup, lookup, lookup];
